[package]
name = "flux-limiter"
version = "0.8.2"
edition = "2024"
authors = ["Jeffery D. Mitchell <crusty-rustacean@gmail.com>"]
description = "A rate limiter based on the Generic Cell Rate Algorithm (GCRA)."
license = "MIT"
homepage = "https://crustyrustacean.github.io/flux-limiter/"
repository = "https://github.com/crustyrustacean/flux-limiter"
documentation = "https://docs.rs/flux-limiter"
keywords = ["rate-limiting", "GCRA", "algorithm", "throttling"]
categories = ["network-programming", "algorithms"]
readme = "README.md"
publish = true

[dependencies]
dashmap = "6.2.1"

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "docsrs"]